name: Releases Builder
on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:         
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check-out repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
           python-version: '3.10.11'

      - name: Init Environment-Windows
        if: ${{ runner.os == 'Windows' }}
        run: |
          echo ("NASTOOL_CONFIG=D:/Nastools/config/config.yaml") >> $env:GITHUB_ENV
          echo $env:NASTOOL_CONFIG
        shell: pwsh

      - name: Init Environment-Linux
        if: ${{ runner.os == 'Linux'}}
        run: |
          echo ("NASTOOL_CONFIG=/home/runner/work/Nastools/config/config.yaml") >> $env:GITHUB_ENV
          echo $env:NASTOOL_CONFIG
        shell: pwsh
        
      - name: Init Environment-Macos
        if: ${{ runner.os == 'macos' }}
        run: |
          echo ("NASTOOL_CONFIG=/Nastools/config/config.yaml") >> $env:GITHUB_ENV
          echo $env:NASTOOL_CONFIG
        shell: pwsh
    
      - name: Install your Dependencies
        run: |
          pip install -r requirements.txt

      - name: Build Executable with Nuitka-Windows
        if: ${{ runner.os == 'Windows' }}
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: run.py
          onefile: true
          enable-plugin: 'upx'
          upx-binary: "package/rely/upx.exe"
          windows-icon-from-ico: "package/nas-tools.ico"
          
      - name: Build Executable with Nuitka-Linux
        if: ${{ runner.os == 'Linux' }}
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: run.py
          onefile: true
          enable-plugin: 'upx'
          upx-binary: "package/rely/upx"
          windows-icon-from-ico: "package/nas-tools.ico"

      - name: Build Executable with Nuitka-Macos
        if: ${{ runner.os == 'Macos' }}
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: run.py
          onefile: true
          macos-app-icon: "package/nas-tools.ico"
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
           name: ${{ runner.os }} Build
           path: | # match what's created for the 3 OSes
              build/*.exe
              build/*.bin
              build/*.app/**/*
            